### PR TITLE
Add emitter

### PR DESCRIPTION
**Pull request by gmlewis**
This PR adds a new underlying queuing technology to "vice" called Emitter which is a high-performance, low-latency, and secure platform based on MQTT. More details can be found at [emitter.io](https://emitter.io).

### CODE REVIEW

**Comment by gmlewis** [comment]
friendly ping

**Comment by ojizero** [comment]
@gmlewis thanks a ton for your contribution! 

Apologies for the delay GitHub didn't push a notification my way when you first opened it and I've been on vacation followed by being swarmed at work and didn't notice it!

I'll give it a look over the weekend!

**Comment by ojizero** [comment]
An initial question (and forgive me if it's too obvious but I'm not 100% expert in MQTT + Emitter) but do you think it is necessary to have an explicit version for Emitter as oppose to having a general purpose MQTT driver that can be configured to use Emitter or other MQTT implementations (kinda like an extension to #56) 🤔

**Comment by gmlewis** [comment]
Hmmm... that's an excellent question, @ojizero - and honestly, since I wrote that PR, I've been learning more about nats.io and am wondering if I should change my current systems to start using nats.io and stop using emitter.io. At the time, I thought Emitter provided some really nice features like the securing of channels, but now I'm kinda wondering if there is added benefit.

If you come to the same conclusion, then I'm totally fine if you just want to simply close this PR. :grin:

**Pull request closed without merging**
