### PR TITLE
add jitter to exponential backoff wrapper

### PR DESCRIPTION
**Pull request by dan-compton**
I was thinking something like the following.  Did this quickly so be wary

### CODE REVIEW

**Comment by dan-compton** [comment]
Looks like transient failure in build

**Comment by matryer** [comment]
Looks like a code problem:

```
backoff/backoff.go:4: imported and not used: "fmt"
```

Maybe run go fmt and goimports or something on your code? You'll catch these little annoying bugs.

**Comment by HeavyHorst** [comment]
The nsq implementation calls
```go
err = backoff.Do(1*time.Second, 10*time.Minute, 0, func() error {
		return t.ConnectConsumer(consumer)
})
```
Notice that maxCalls is zero, which means retry forever in the original implementation.
Your implementation returns immediately with a nil error
```go
for rc := 0; rc < maxTries; rc++
```

I think thats why the test hangs forever.

**Comment by matryer** [comment]
Definitely shouldn’t be retrying forever.

**Comment by HeavyHorst** [comment]
@dan-compton  can you change 
```go
err = backoff.Do(1*time.Second, 10*time.Minute, 0, func() error {
		return t.ConnectConsumer(consumer)
})
```

to 

```go
err = backoff.Do(1*time.Second, 10*time.Minute, 10, func() error {
		return t.ConnectConsumer(consumer)
})
```
in nsq.go line 113

**Comment by dan-compton** [comment]
Sure, although should we us NSQ defaults here?
 Default max back off is 2 minutes and max retries is 5 IIRC.  

Also, are we comfortable with the behavior around max and min calls?  For example passing ...0 and having no function call occur?  Do we need to wrap errors for exceeded retry count in a sentinel context or expose another means of determining whether or not the retry count was exceeded?

**Pull request closed without merging**
