### PR TITLE
Updates for SQS writers

### PR DESCRIPTION
**Pull request by jsteenb2**
This PR adds the ability to batch publishes to SQS (a necessity for high throughput). This PR also adds the ability to create multi publishers to SQS. The constructor dictates batch-size and number of publishers. The external API doesn't change, however, the throughput with SQS will dramatically improve.

### CODE REVIEW

**Comment by matryer** [comment]
```
/home/travis/gopath/src/github.com/matryer/vice/queues/nats/nats_test.go:25:44: 2-valued uuid.NewV4() (value of type (github.com/satori/go.uuid.UUID, error)) where single value is expected
```

**Comment by matryer** [comment]
@jsteenb2 thanks for this - it looks like we've been hit for the first time with a dependency issue.

**Comment by matryer** [comment]
(please pull from `master` - I fixed that broken test)

**Comment by jsteenb2** [comment]
@matryer the branch was rebased off of master with your fixes 👍

**Pull request merged**
