### PR TITLE
How about Codeship Pro?

### PR DESCRIPTION
**Pull request by GeorgeMac**
Thought I would be cheeky and whip up a quick example of what running your test suite on Codeship Pro would be like. As per my comment in https://github.com/matryer/vice/issues/22

All this is currently configured to do is:
1. check everything has bee run with `gofmt`
2. ensure the `queues/redis` package tests pass

https://app.codeship.com/projects/237216/builds/ab3ca69c-325a-414c-abcb-a11c03f83a79

If you like it I can configure the rest of the queue types and explain how the configuration works. Basically `codeship-services.yml` is very similar to `docker-compose.yml` v1. V2 components are under construction.

### CODE REVIEW

**Comment by matryer** [comment]
image

**Comment by GeorgeMac** [comment]
@matryer sorry I learn something new everyday about the product I work on. Apparently we don't have a public interface for any type of project. I didn't realize we had this limitation and now I understand better why we don't work well with open source XD

I will close this, if you feel that you don't need to share the details of your builds publicly in exchange for more complex configuration and faster build times I can get it integrated for you. But I imagine visibility in to build failures for any contributor is more favorable.

**Comment by matryer** [comment]
I’d love a “Free for open-source” option :) Would be a great way to promote your service to the right people.

**Comment by GeorgeMac** [comment]
Codeship Pro + Basic are free for open source, but sadly we don't let you share the build dashboard with the public :( You can have a badge still, but that is it. Which is sad :( Thank you for inadvertently bringing this to my attention XD

**Pull request closed without merging**
